name: moldox
channels:
  - schrodinger
  - pdbfixer
  - conda-forge
  - salilab
  - defaults
dependencies:
  - python=3.8
  - conda-forge::schrodinger::pymol-bundle
  - conda-forge::openbabel
  - conda-forge::rdkit
  - conda-forge::MDAnalysis
  - conda-forge::pdbfixer
  - pip:
    - meeko==0.2
    - vina
    - py3Dmol
    - jupyter

