
package:
  name: "moldox"
  version: "1.0.0"

source:
  git_rev: main
  git_url: https://github.com/derekvantilborg/MolDox

requirements:
  host:
    - python
    - setuptools
  build:
    - python=3.8
  run:
    - python=3.8
    - pymol-bundle
    - openbabel
    - rdkit
    - MDAnalysis
    - pdbfixer
    - vina
    - py3Dmol


about:
  home: https://github.com/derekvantilborg/MolDox
  license: MIT
  license_familY: MIT
  license_file: LICENSE
  summary: "Easy Molecular Docking"

